server:
  servlet:
    context-path: "/"

spring:
  security:
    user:
      name: user
      password: admin
    basic:
      enabled: false
  application:
    name: edu
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      username: postgres
      password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  upload:
    directory: ./uploads
  web:
    resources:
      static-locations: classpath:/public/, classpath:/static/, classpath:/images/
  mvc:
    servlet:
      load-on-startup: 1

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
